ECTPPING: Fixing build error caused with newer kernels
When compiling the CTP application with x86, we see the following
error:

ectpping.c:1345:20: error: ‘SIOCGSTAMP’ undeclared (first use in this function); did you mean ‘SIOCGARP’?
 1345 |  ioctl(*rx_sockfd, SIOCGSTAMP, pkt_arrived);
      |                    ^~~~~~~~~~
      |                    SIOCGARP

This error is because the definition of SIOCGSTAMP has moved to
linux/sockios.h in newer kernels. Adding this header file fixes
the build

Signed-off-by: Bilal Wasim <bilalwasim676@gmail.com>