MAKEFILE: Fix linker error
When building the ctp application with x86, we see the linker error:

/usr/bin/ld: /tmp/ccEKSGHV.o: in function `main':
ectpping.c:(.text+0x19d): undefined reference to `pthread_create'
/usr/bin/ld: ectpping.c:(.text+0x1ca): undefined reference to `pthread_create'
/usr/bin/ld: ectpping.c:(.text+0x1e4): undefined reference to `pthread_join'

This error is caused because the Makefiles lists the library before the
source/object file and it should be opposite in general. Fixing the order
gets rid of the linker failures..

Signed-off-by: Bilal Wasim <bilalwasim676@gmail.com>